# Generated by Django 4.2 on 2025-11-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='John Paolo A. Silvano', max_length=200)),
                ('title', models.CharField(default='Junior Python/Django Developer', max_length=200)),
                ('email', models.EmailField(default='johnpaolosilvano24@gmail.com', max_length=254)),
                ('github', models.CharField(blank=True, default='github.com/Johnz010823', max_length=200)),
                ('linkedin', models.CharField(blank=True, default='John Paolo Silvano', max_length=200)),
                ('short_intro', models.TextField(default='I am a Junior Developer who enjoys converting ideas into functional applications using Python, Django, HTML/CSS, and JavaScript.')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('role', models.CharField(blank=True, max_length=200)),
                ('tech_stack', models.CharField(blank=True, max_length=300)),
                ('features', models.TextField(blank=True, help_text='Comma or newline separated features.')),
                ('github_link', models.URLField(blank=True)),
                ('demo_link', models.URLField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='project_screens/')),
                ('order', models.IntegerField(default=0, help_text='Lower number appears first.')),
            ],
        ),
    ]
